// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WildBerries;
//
//    var getterProductCartDetailFromJson = GetterProductCartDetailFromJson.FromJson(jsonString);

namespace WildBerries2
{
    using Newtonsoft.Json;

    public partial class GetterProductCartDetailFromJson
    {
        [JsonProperty("state")]
        public long State { get; set; }

        [JsonProperty("params")]
        public Params Params { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Product
    {

        [JsonProperty("root")]
        public long Root { get; set; }

        [JsonProperty("kindId")]
        public long KindId { get; set; }

        [JsonProperty("subjectId")]
        public long SubjectId { get; set; }

        [JsonProperty("subjectParentId")]
        public long SubjectParentId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("brand")]
        public string Brand { get; set; }

        [JsonProperty("brandId")]
        public long BrandId { get; set; }

        [JsonProperty("siteBrandId")]
        public long SiteBrandId { get; set; }

        [JsonProperty("supplier")]
        public string Supplier { get; set; }

        [JsonProperty("priceU")]
        public long PriceU { get; set; }

        [JsonProperty("salePriceU")]
        public long SalePriceU { get; set; }

        [JsonProperty("logisticsCost")]
        public long LogisticsCost { get; set; }

        [JsonProperty("sale")]
        public long Sale { get; set; }

        [JsonProperty("extended")]
        public Extended Extended { get; set; }

        [JsonProperty("saleConditions")]
        public long SaleConditions { get; set; }

        [JsonProperty("returnCost")]
        public long ReturnCost { get; set; }

        [JsonProperty("pics")]
        public long Pics { get; set; }

        [JsonProperty("rating")]
        public long Rating { get; set; }

        [JsonProperty("reviewRating")]
        public double ReviewRating { get; set; }

        [JsonProperty("feedbacks")]
        public long Feedbacks { get; set; }

        [JsonProperty("volume")]
        public long Volume { get; set; }

        [JsonProperty("viewFlags")]
        public long ViewFlags { get; set; }

        [JsonProperty("diffPrice")]
        public bool DiffPrice { get; set; }
    }

    public partial class Extended
    {
        [JsonProperty("basicSale")]
        public long BasicSale { get; set; }

        [JsonProperty("basicPriceU")]
        public long BasicPriceU { get; set; }
    }

    public partial class Params
    {
        [JsonProperty("version")]
        public long Version { get; set; }

        [JsonProperty("curr")]
        public string Curr { get; set; }

        [JsonProperty("payloadVersion")]
        public long PayloadVersion { get; set; }
    }

    public partial class GetterProductCartDetailFromJson
    {
        public static GetterProductCartDetailFromJson FromJson(string json) => JsonConvert.DeserializeObject<GetterProductCartDetailFromJson>(json, WildBerries2.Converter.Settings);
    }
}
